---
    dt: 0.1
    noise:
      - - 490.3325
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      - - 0.0
        - 274.58619999999996
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      - - 0.0
        - 0.0
        - 127.48644999999999
        - 0.0
        - 0.0
        - 0.0
      - - 0.0
        - 0.0
        - 0.0
        - 0.0001
        - 0.0
        - 0.0
      - - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0001
        - 0.0
      - - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 274.58619999999996