---
    dt: 0.1
    noise:
      - - 100.3325
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      - - 0.0
        - 274.58619999999996
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      - - 0.0
        - 0.0
        - 300.
        - 0.0
        - 0.0
        - 0.0
      - - 0.0
        - 0.0
        - 0.0
        - 0.00001
        - 0.0
        - 0.0
      - - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.00001
        - 0.0
      - - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 100.