from .controllers.controller_base import ControllerBase

def get_controller(model,
                   cost,
                   k,
                   tau,
                   dt,
                   sDim,
                   aDim,
                   lam,
                   upsilon,
                   sigma,
                   normalizeCost,
                   filterSeq,
                   log,
                   logPath,
                   gif,
                   graphMode,
                   debug,
                   configDict,
                   taskDict,
                   modelDict):
    
    return ControllerBase(model=model,
                          cost=cost,
                          k=k,
                          tau=tau,
                          dt=dt,
                          sDim=sDim,
                          aDim=aDim,
                          lam=lam,
                          upsilon=upsilon,
                          sigma=sigma,
                          normalizeCost=normalizeCost,
                          filterSeq=filterSeq,
                          log=log,
                          logPath=logPath,
                          gif=gif,
                          graphMode=graphMode,
                          debug=debug,
                          configDict=configDict,
                          taskDict=taskDict,
                          modelDict=modelDict)