---
dataset_params:
  samples: 5000
  steps: 15
  history: 1
  dir: "data/csv/training_csv/"
  split: 0.7
  v_frame: "body"
  dv_frame: "body"
  frame: "body"
  act_normed: True
  out_normed: False
  se3: True
  batch_size: 512
  shuffle: True
  num_workers: 8

model:
  frame: "body"
  training: True
  type: "auv_lstm"
  se3: True
  history: 1
  lstm:
    lstm_layer: 1
    lstm_hidden_size: 64
    bias: True
  fc:
    topology: [128, 128]
    activation: "LeakyRelu"
    bias: True
    batch_norm: False
    relu_neg_slope: 0.1

loss:
  type: "traj"
  traj: 1.
  vel: 1.
  dv: 1.

optim:
  type: "Adam"
  lr: 1.e-4
  epochs: 100

log:
  path: trained_models/lstm
  stamped: True
  ckpt_steps: 10