---
logging:
  project: "nn"
  notes: ""
  tags: ["baseline"]

data_loader_params:
  batch_size: 512
  shuffle: True
  num_workers: 8

dataset_params:
  samples: 10
  steps: 15
  history: 4
  dir: "data/csv/tests"
  split: 0.7
  v_frame: "body"
  dv_frame: "body"
  frame: "body"
  act_normed: True
  out_normed: False
  se3: True
  batch_size: 512
  shuffle: True
  num_workers: 8

loss:
  type: "traj"
  traj: 1.
  vel: 1.
  dv: 1.

optim:
  type: "Adam"
  lr: 1.e-4
  epochs: 2

model:
  frame: "body"
  training: True
  type: "auv_nn"
  se3: True
  history: 4
  fc:
    topology: [128, 128, 128]
    activation: "LeakyRelu"
    bias: True
    batch_norm: False
    relu_neg_slope: 0.1

log:
  path: trained_models/debug
  stamped: True
  ckpt_steps: 2

