---
type: "lagged_controller"
history: 1
steps: 1
dt: 0.1
noise:
  - - 0.01
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.01
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.05
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.01
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.01
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.01