---
    type: "static_quat"
    diag: true
    goal:
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    Q:
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 10.0
      
